### ISSUE TITLE
'Exception in thread "main" java.lang.Exception: called children on a leaf node'

### ISSUE THREAD

**Issue by dannyg28** [SagaHealthcareIT/mirthsync#2]
```Uploading from src/Channels to /channelgroups
Exception in thread "main" java.lang.Exception: called children on a leaf node
	at clojure.zip$children.invokeStatic(zip.clj:80)
	at clojure.zip$append_child.invokeStatic(zip.clj:223)
	at clojure.zip$append_child.invoke(zip.clj:223)
	at mirthsync.apis$pre_node_action.invokeStatic(apis.clj:72)
	at mirthsync.apis$pre_node_action.invoke(apis.clj:52)
	at clojure.core$partial$fn__5828.invoke(core.clj:2638)
	at mirthsync.actions$process.invokeStatic(actions.clj:65)
	at mirthsync.actions$process.invoke(actions.clj:54)
	at mirthsync.actions$upload.invokeStatic(actions.clj:89)
	at mirthsync.actions$upload.invoke(actions.clj:82)
	at mirthsync.apis$apis_action.invokeStatic(apis.clj:225)
	at mirthsync.apis$apis_action.invoke(apis.clj:219)
	at mirthsync.core$run$fn__3047.invoke(core.clj:23)
	at mirthsync.http_client$with_authentication.invokeStatic(http_client.clj:51)
	at mirthsync.http_client$with_authentication.invoke(http_client.clj:39)
	at mirthsync.core$run.invokeStatic(core.clj:19)
	at mirthsync.core$run.invoke(core.clj:8)
	at mirthsync.core$_main.invokeStatic(core.clj:39)
	at mirthsync.core$_main.doInvoke(core.clj:35)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at mirthsync.core.main(Unknown Source)
```
I get the above error trying to use our Jenkins server to deploy our updated mirth code to our other environments. I'm able to use the same exact script I'm calling in the Jenkins' job on my local machine, both using my windows powershell terminal and in my Linux subsystem terminal. 

both the Jenkins server and my linux terminal are running this java version 
```openjdk version 1.8.0_191
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
 ```
and I'm running the most recent release snapshot

Any help anyone can provide I would be very grateful for.

**Comment by jessesaga** [comment]
Are you explicitly specifying the target directory `-t` parameter for mirthsync in all environments? I'm wondering if it could be a relative path issue. 
Also, can you capture the Mirthsync's stdout when running? What stage is it failing at?

**Comment by dannyg28** [comment]
```Authenticating to server at https://integration.stg.4tellus.net/api as jenkins
Uploading from src/. to /server/configurationMap
Uploading from src/GlobalScripts to /server/globalScripts
Uploading from src/CodeTemplates to /codeTemplateLibraries
Uploading from src/CodeTemplates to /codeTemplates
Uploading from src/Channels to /channelgroups
Exception in thread "main" java.lang.Exception: called children on a leaf node
```

That's the exact point in which it fails everytime. I actually managed to work around it by creating a Windows Worker node for my Jenkins master to use to deploy. It seems like its an issue of deploying from Linux to Windows. I was able to deploy locally using my computer's Linux for Windows Subsystem but every pure Linux server I tested on got the same error at the same point.

**Comment by jessesaga** [comment]
Spaces in names and pure Linux to Windows are both tested configurations and should work fine.

Maybe it's a path issue either involving letter case-sensitivity in Linux or backslash vs forward slash in the `-t` parameter?
