### ISSUE TITLE
Authentication issue with Connect 3.12

### ISSUE THREAD

**Issue by doggit** [SagaHealthcareIT/mirthsync#25]
mirthsync version: 2.1.1
connect version: 3.12

MirthSync is returning a 400 error when authenticating, which is likely related to a CSRF fix in Connect 3.12 (https://github.com/nextgenhealthcare/connect/wiki/3.12.0---What's-New) and the new `require-requested-with` setting:

`
/usr/bin/java
found java executable in PATH
version 11.0.11
Authenticating to server at https://localhost:8443/api as admin
clojure.lang.ExceptionInfo: clj-http: status 400 {:cached nil, :request-time 270, :repeatable? false, :protocol-version {:name "HTTP", :major 1, :minor 1}, :streaming? true, :http-client #object[org.apache.http.impl.client.InternalHttpClient 0x4f486211 "org.apache.http.impl.client.InternalHttpClient@4f486211"], :chunked? false, :type :clj-http.client/unexceptional-status, :reason-phrase "Bad Request", :headers {"Access-Control-Allow-Headers" "Content-Type", "Server" "Jetty(9.4.21.v20190926)", "Content-Type" "text/html;charset=iso-8859-1", "Access-Control-Allow-Origin" "*", "Content-Length" "653", "X-Frame-Options" "DENY", "Connection" "close", "Access-Control-Allow-Methods" "GET, POST, DELETE, PUT", "Access-Control-Allow-Credentials" "false", "Content-Security-Policy" "frame-ancestors 'none'", "Cache-Control" "must-revalidate,no-cache,no-store"}, :orig-content-encoding nil, :status 400, :length 653, :body "<html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\"/>\n<title>Error 400 All requests must have &apos;X-Requested-With&apos; header</title>\n</head>\n<body><h2>HTTP ERROR 400 All requests must have &apos;X-Requested-With&apos; header</h2>\n<table>\n<tr><th>URI:</th><td>/api/users/_login</td></tr>\n<tr><th>STATUS:</th><td>400</td></tr>\n<tr><th>MESSAGE:</th><td>All requests must have &apos;X-Requested-With&apos; header</td></tr>\n<tr><th>SERVLET:</th><td>org.glassfish.jersey.servlet.ServletContainer-7dd8c3da</td></tr>\n</table>\n<hr><a href=\"http://eclipse.org/jetty\">Powered by Jetty:// 9.4.21.v20190926</a><hr/>\n\n</body>\n</html>\n", :trace-redirects []}
	at slingshot.support$stack_trace.invoke(support.clj:201)
	at clj_http.client$exceptions_response.invokeStatic(client.clj:240)
	at clj_http.client$exceptions_response.invoke(client.clj:231)
	at clj_http.client$wrap_exceptions$fn__2641.invoke(client.clj:249)
	at clj_http.client$wrap_accept$fn__2851.invoke(client.clj:726)
	at clj_http.client$wrap_accept_encoding$fn__2858.invoke(client.clj:748)
	at clj_http.client$wrap_content_type$fn__2845.invoke(client.clj:709)
	at clj_http.client$wrap_form_params$fn__2944.invoke(client.clj:950)
	at clj_http.client$wrap_nested_params$fn__2965.invoke(client.clj:984)
	at clj_http.client$wrap_flatten_nested_params$fn__2974.invoke(client.clj:1008)
	at clj_http.client$wrap_method$fn__2912.invoke(client.clj:884)
	at clj_http.cookies$wrap_cookies$fn__1320.invoke(cookies.clj:131)
	at clj_http.links$wrap_links$fn__2446.invoke(links.clj:63)
	at clj_http.client$wrap_unknown_host$fn__2982.invoke(client.clj:1037)
	at clj_http.client$request_STAR_.invokeStatic(client.clj:1165)
	at clj_http.client$request_STAR_.invoke(client.clj:1158)
	at clj_http.client$post.invokeStatic(client.clj:1183)
	at clj_http.client$post.doInvoke(client.clj:1179)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at mirthsync.http_client$with_authentication.invokeStatic(http_client.clj:47)
	at mirthsync.http_client$with_authentication.invoke(http_client.clj:41)
	at mirthsync.core$run.invokeStatic(core.clj:21)
	at mirthsync.core$run.invoke(core.clj:10)
	at mirthsync.core$main_func$fn__3394.invoke(core.clj:46)
	at mirthsync.core$main_func.invokeStatic(core.clj:45)
	at mirthsync.core$main_func.doInvoke(core.clj:37)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at mirthsync.core$_main.invokeStatic(core.clj:57)
	at mirthsync.core$_main.doInvoke(core.clj:55)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at mirthsync.core.main(Unknown Source)
clj-http: status 400
`

Thanks for this project!

**Comment by jessesaga** [comment]
Thanks for the report and suggested fix! I'll look into replicating this and adding the header soon.
