### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by shanedewitt** [SagaHealthcareIT/mirthsync#28]
I am using mirth 3.11 on an appliance.

ln -s mirthsync-2.1.1/lib/mirthsync-2.1.1-standalone.jar mirthsync.jar

mkdir mirthtest

java -jar mirthsync.jar -s https://172.20.100.61:8443/api -u admin -p admin pull -t mirthtest
Authenticating to server at https://172.20.100.61:8443/api as admin
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:200)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:313)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at clj_http.core$request.invokeStatic(core.clj:641)
	at clj_http.core$request.invoke(core.clj:566)
	at clj_http.core$request.invokeStatic(core.clj:567)
	at clj_http.core$request.invoke(core.clj:566)
	at clojure.lang.Var.invoke(Var.java:384)
	at clj_http.client$wrap_request_timing$fn__2997.invoke(client.clj:1074)
	at clj_http.headers$wrap_header_map$fn__2113.invoke(headers.clj:152)
	at clj_http.client$wrap_query_params$fn__2887.invoke(client.clj:808)
	at clj_http.client$wrap_basic_auth$fn__2893.invoke(client.clj:831)
	at clj_http.client$wrap_oauth$fn__2898.invoke(client.clj:848)
	at clj_http.client$wrap_user_info$fn__2907.invoke(client.clj:868)
	at clj_http.client$wrap_url$fn__2979.invoke(client.clj:1026)
	at clj_http.client$wrap_decompression$fn__2688.invoke(client.clj:415)
	at clj_http.client$wrap_input_coercion$fn__2811.invoke(client.clj:628)
	at clj_http.client$wrap_additional_header_parsing$fn__2836.invoke(client.clj:683)
	at clj_http.client$wrap_output_coercion$fn__2798.invoke(client.clj:572)
	at clj_http.client$wrap_exceptions$fn__2641.invoke(client.clj:249)
	at clj_http.client$wrap_accept$fn__2851.invoke(client.clj:726)
	at clj_http.client$wrap_accept_encoding$fn__2858.invoke(client.clj:748)
	at clj_http.client$wrap_content_type$fn__2845.invoke(client.clj:709)
	at clj_http.client$wrap_form_params$fn__2944.invoke(client.clj:950)
	at clj_http.client$wrap_nested_params$fn__2965.invoke(client.clj:984)
	at clj_http.client$wrap_flatten_nested_params$fn__2974.invoke(client.clj:1008)
	at clj_http.client$wrap_method$fn__2912.invoke(client.clj:884)
	at clj_http.cookies$wrap_cookies$fn__1320.invoke(cookies.clj:131)
	at clj_http.links$wrap_links$fn__2446.invoke(links.clj:63)
	at clj_http.client$wrap_unknown_host$fn__2982.invoke(client.clj:1037)
	at clj_http.client$request_STAR_.invokeStatic(client.clj:1165)
	at clj_http.client$request_STAR_.invoke(client.clj:1158)
	at clj_http.client$post.invokeStatic(client.clj:1183)
	at clj_http.client$post.doInvoke(client.clj:1179)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at mirthsync.http_client$with_authentication.invokeStatic(http_client.clj:47)
	at mirthsync.http_client$with_authentication.invoke(http_client.clj:41)
	at mirthsync.core$run.invokeStatic(core.clj:21)
	at mirthsync.core$run.invoke(core.clj:10)
	at mirthsync.core$main_func$fn__3394.invoke(core.clj:46)
	at mirthsync.core$main_func.invokeStatic(core.clj:45)
	at mirthsync.core$main_func.doInvoke(core.clj:37)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at mirthsync.core$_main.invokeStatic(core.clj:57)
	at mirthsync.core$_main.doInvoke(core.clj:55)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at mirthsync.core.main(Unknown Source)
unable to find valid certification path to requested target

**Comment by jessesaga** [comment]
You need to use -i, --ignore-cert-warnings. You can see all of the supported flags with --help or by running the command without options.

**Comment by shanedewitt** [comment]
That worked, thanks.
