### ISSUE TITLE
HTTP method POST is not supported by this URL

### ISSUE THREAD

**Issue by swar00p** [SagaHealthcareIT/mirthsync#4]
When I try to use mirthSync to connect to a Mirth server in our workplace, I get the following response:

/usr/bin/java
found java executable in PATH
version 1.8.0_211
Authenticating to server at http://10.250.10.100:8000/api as admin
Exception in thread "main" clojure.lang.ExceptionInfo: clj-http: status 405 {:cached nil, :request-time 333, :repeatable? false, :protocol-version {:name "HTTP", :major 1, :minor 1}, :streaming? true, :http-client #object[org.apache.http.impl.client.InternalHttpClient 0x7c2a69b4 "org.apache.http.impl.client.InternalHttpClient@7c2a69b4"], :chunked? false, :type :clj-http.client/unexceptional-status, :reason-phrase "HTTP method POST is not supported by this URL", :headers {"Date" "Thu, 17 Oct 2019 17:22:44 GMT", "Cache-Control" "must-revalidate,no-cache,no-store", "Content-Type" "text/html;charset=iso-8859-1", "Content-Length" "369", "Connection" "close", "Server" "Jetty(9.3.14.v20161028)"}, :orig-content-encoding nil, :status 405, :length 369, :body "<html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=ISO-8859-1\"/>\n<title>Error 405 </title>\n</head>\n<body>\n<h2>HTTP ERROR: 405</h2>\n<p>Problem accessing /api/users/_login. Reason:\n<pre>    HTTP method POST is not supported by this URL</pre></p>\n<hr /><a href=\"http://eclipse.org/jetty\">Powered by Jetty:// 9.3.14.v20161028</a><hr/>\n</body>\n</html>\n", :trace-redirects []}
	at slingshot.support$stack_trace.invoke(support.clj:201)
	at clj_http.client$exceptions_response.invokeStatic(client.clj:245)
	at clj_http.client$exceptions_response.invoke(client.clj:236)
	at clj_http.client$wrap_exceptions$fn__2394.invoke(client.clj:254)
	at clj_http.client$wrap_accept$fn__2596.invoke(client.clj:737)
	at clj_http.client$wrap_accept_encoding$fn__2603.invoke(client.clj:759)
	at clj_http.client$wrap_content_type$fn__2590.invoke(client.clj:720)
	at clj_http.client$wrap_form_params$fn__2689.invoke(client.clj:961)
	at clj_http.client$wrap_nested_params$fn__2710.invoke(client.clj:995)
	at clj_http.client$wrap_flatten_nested_params$fn__2719.invoke(client.clj:1019)
	at clj_http.client$wrap_method$fn__2657.invoke(client.clj:895)
	at clj_http.cookies$wrap_cookies$fn__1074.invoke(cookies.clj:131)
	at clj_http.links$wrap_links$fn__2199.invoke(links.clj:63)
	at clj_http.client$wrap_unknown_host$fn__2727.invoke(client.clj:1048)
	at clj_http.client$request_STAR_.invokeStatic(client.clj:1176)
	at clj_http.client$request_STAR_.invoke(client.clj:1169)
	at clj_http.client$post.invokeStatic(client.clj:1194)
	at clj_http.client$post.doInvoke(client.clj:1190)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at mirthsync.http_client$with_authentication.invokeStatic(http_client.clj:45)
	at mirthsync.http_client$with_authentication.invoke(http_client.clj:39)
	at mirthsync.core$run.invokeStatic(core.clj:19)
	at mirthsync.core$run.invoke(core.clj:8)
	at mirthsync.core$_main.invokeStatic(core.clj:39)
	at mirthsync.core$_main.doInvoke(core.clj:35)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at mirthsync.core.main(Unknown Source)

**Comment by jessesaga** [comment]
Have you tried using it with the https version of that url? 

https://10.250.10.100:8443/api

**Comment by swar00p** [comment]
I tried it just now and got this error instead:

/usr/bin/java
found java executable in PATH
version 1.8.0_211
Authenticating to server at https://10.250.10.100:8000/api as admin
Exception in thread "main" javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
	at sun.security.ssl.InputRecord.read(InputRecord.java:527)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:325)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at clj_http.core$request.invokeStatic(core.clj:626)
	at clj_http.core$request.invoke(core.clj:554)
	at clj_http.core$request.invokeStatic(core.clj:555)
	at clj_http.core$request.invoke(core.clj:554)
	at clojure.lang.Var.invoke(Var.java:384)
	at clj_http.client$wrap_request_timing$fn__2742.invoke(client.clj:1085)
	at clj_http.headers$wrap_header_map$fn__1867.invoke(headers.clj:147)
	at clj_http.client$wrap_query_params$fn__2632.invoke(client.clj:819)
	at clj_http.client$wrap_basic_auth$fn__2638.invoke(client.clj:842)
	at clj_http.client$wrap_oauth$fn__2643.invoke(client.clj:859)
	at clj_http.client$wrap_user_info$fn__2652.invoke(client.clj:879)
	at clj_http.client$wrap_url$fn__2724.invoke(client.clj:1037)
	at clj_http.client$wrap_decompression$fn__2441.invoke(client.clj:420)
	at clj_http.client$wrap_input_coercion$fn__2556.invoke(client.clj:639)
	at clj_http.client$wrap_additional_header_parsing$fn__2581.invoke(client.clj:694)
	at clj_http.client$wrap_output_coercion$fn__2543.invoke(client.clj:583)
	at clj_http.client$wrap_exceptions$fn__2394.invoke(client.clj:254)
	at clj_http.client$wrap_accept$fn__2596.invoke(client.clj:737)
	at clj_http.client$wrap_accept_encoding$fn__2603.invoke(client.clj:759)
	at clj_http.client$wrap_content_type$fn__2590.invoke(client.clj:720)
	at clj_http.client$wrap_form_params$fn__2689.invoke(client.clj:961)
	at clj_http.client$wrap_nested_params$fn__2710.invoke(client.clj:995)
	at clj_http.client$wrap_flatten_nested_params$fn__2719.invoke(client.clj:1019)
	at clj_http.client$wrap_method$fn__2657.invoke(client.clj:895)
	at clj_http.cookies$wrap_cookies$fn__1074.invoke(cookies.clj:131)
	at clj_http.links$wrap_links$fn__2199.invoke(links.clj:63)
	at clj_http.client$wrap_unknown_host$fn__2727.invoke(client.clj:1048)
	at clj_http.client$request_STAR_.invokeStatic(client.clj:1176)
	at clj_http.client$request_STAR_.invoke(client.clj:1169)
	at clj_http.client$post.invokeStatic(client.clj:1194)
	at clj_http.client$post.doInvoke(client.clj:1190)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at mirthsync.http_client$with_authentication.invokeStatic(http_client.clj:45)
	at mirthsync.http_client$with_authentication.invoke(http_client.clj:39)
	at mirthsync.core$run.invokeStatic(core.clj:19)
	at mirthsync.core$run.invoke(core.clj:8)
	at mirthsync.core$_main.invokeStatic(core.clj:39)
	at mirthsync.core$_main.doInvoke(core.clj:35)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at mirthsync.core.main(Unknown Source)

**Comment by jessesaga** [comment]
You used https but you're referencing an http port. Instead of 8000 it should be 8443.
