### ISSUE TITLE
Inner actions names may not be valid filesystem names

### ISSUE THREAD

**Issue by carm-afea** [SagaHealthcareIT/mirthsync#47]
I have this transformer step called: "`patient.identifier.extCode -> patient.identifier[type = 'PI'].value`"
When pulling, this is the result:

`.\Channels\MPI_NEW\MPI_ADT_DB_READER\destinationConnector-ToDispatcher-transformer-step-0-patient.identifier.extCode -> patient.identifier[type = 'PI'].value.js The filename, directory name, or volume label syntax is incorrect.`

I can change that with no consequences, but that's not always the case and not always simple to achieve, especially when you've got lots of channels and you find out about such a limitation at the very last minute.

**Comment by jbeckers** [comment]
Seeing the same thing with channel names, group names, etc.

e.g.
```
 File: .\v1000test\Channels\MMT: CM\index.xml
java.io.FileNotFoundException: .\v1000test\Channels\MMT: CM\index.xml (De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
```
