### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by yimengZJl** [SagaHealthcareIT/mirthsync#5]
This error occurred when I was 
![5(R@L4GF`$1KAM`QI)ODETS](https://user-images.githubusercontent.com/34049542/72424210-95852180-37c0-11ea-87f0-c41d0bbc6ccb.png)
pushing code to the server

**Comment by yimengZJl** [comment]
\CodeTemplates to /codeTemplateLibraries
Exception in thread "main" java.lang.Exception: called children on a leaf node
        at clojure.zip$children.invokeStatic(zip.clj:80)
        at clojure.zip$append_child.invokeStatic(zip.clj:223)
        at clojure.zip$append_child.invoke(zip.clj:223)
        at mirthsync.apis$pre_node_action.invokeStatic(apis.clj:72)
        at mirthsync.apis$pre_node_action.invoke(apis.clj:52)
        at clojure.core$partial$fn__5828.invoke(core.clj:2638)
        at mirthsync.actions$process.invokeStatic(actions.clj:65)
        at mirthsync.actions$process.invoke(actions.clj:54)
        at mirthsync.actions$upload.invokeStatic(actions.clj:89)
        at mirthsync.actions$upload.invoke(actions.clj:82)
        at mirthsync.apis$apis_action.invokeStatic(apis.clj:225)
        at mirthsync.apis$apis_action.invoke(apis.clj:219)
        at mirthsync.core$run$fn__3047.invoke(core.clj:23)
        at mirthsync.http_client$with_authentication.invokeStatic(http_client.clj:51)
        at mirthsync.http_client$with_authentication.invoke(http_client.clj:39)
        at mirthsync.core$run.invokeStatic(core.clj:19)
        at mirthsync.core$run.invoke(core.clj:8)
        at mirthsync.core$_main.invokeStatic(core.clj:39)
        at mirthsync.core$_main.doInvoke(core.clj:35)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at mirthsync.core.main(Unknown Source)

**Comment by jessesaga** [comment]
Which mirthsync version are you using? Does the same error happen with the latest snapshot release?
https://github.com/SagaHealthcareIT/mirthsync/releases

Also, what version of Mirth are you running against?

**Comment by yimengZJl** [comment]
Mirth version is 3.7.1 ，The mirthsync versions use 2.0.2 and 2.0.3, respectively.The error is the same

**Comment by yimengZJl** [comment]
Can someone help me?

**Comment by jessesaga** [comment]
Sorry for the delayed response. If this is still an issue that you would like to troubleshoot - let me know. There are new features in the master branch that make it easier to test against multiple versions of Mirth which could be useful in troubleshooting the problem. Also, if you can share a minimal version of your target directory that doesn't have any sensitive information it could assist me in troubleshooting. Best, Jesse
