### ISSUE TITLE
Exception in thread "main" java.lang.Exception: called children on a leaf node

### ISSUE THREAD

**Issue by vikram-rajan** [SagaHealthcareIT/mirthsync#7]
This problem seems to be occurring again. 

The push command works fine when ran against a clean mirth instance. But when I do a force push against an instance which has channels, code templates and global scripts the command fails.

CMD: 
java -jar mirthsync/mirthsync.jar -s https://localhost:8444/api -u admin -p admin push -f -i -t .

Exception:
Authenticating to server at https://localhost:8444/api as admin
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by clojure.lang.InjectedInvoker/0x0000000800b7d440 (file:/Users/vikramrajan/dev/bpm/fhir-mirth/mirthsync/mirthsync.jar) to method com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(java.io.Reader)
WARNING: Please consider reporting this to the maintainers of clojure.lang.InjectedInvoker/0x0000000800b7d440
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Uploading from ./. to /server/configurationMap
	File: ././ConfigurationMap.xml
Uploading from ./GlobalScripts to /server/globalScripts
	File: ./GlobalScripts/globalScripts.xml
Uploading from ./CodeTemplates to /codeTemplateLibraries
	File: ./CodeTemplates/FHIR Helper Functions/index.xml
Exception in thread "main" java.lang.Exception: called children on a leaf node
	at clojure.zip$children.invokeStatic(zip.clj:80)
	at clojure.zip$append_child.invokeStatic(zip.clj:223)
	at clojure.zip$append_child.invoke(zip.clj:223)
	at mirthsync.apis$pre_node_action.invokeStatic(apis.clj:73)
	at mirthsync.apis$pre_node_action.invoke(apis.clj:53)
	at clojure.core$partial$fn__5828.invoke(core.clj:2638)
	at mirthsync.actions$process.invokeStatic(actions.clj:73)
	at mirthsync.actions$process.invoke(actions.clj:62)
	at mirthsync.actions$upload.invokeStatic(actions.clj:97)
	at mirthsync.actions$upload.invoke(actions.clj:90)
	at mirthsync.apis$apis_action.invokeStatic(apis.clj:277)
	at mirthsync.apis$apis_action.invoke(apis.clj:271)
	at mirthsync.core$run$fn__3283.invoke(core.clj:25)
	at mirthsync.http_client$with_authentication.invokeStatic(http_client.clj:49)
	at mirthsync.http_client$with_authentication.invoke(http_client.clj:37)
	at mirthsync.core$run.invokeStatic(core.clj:21)
	at mirthsync.core$run.invoke(core.clj:10)
	at mirthsync.core$_main.invokeStatic(core.clj:48)
	at mirthsync.core$_main.doInvoke(core.clj:39)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at mirthsync.core.main(Unknown Source)

**Comment by vikram-rajan** [comment]
Child leaf node exception is caused by having multiple code template libraries. The workaround was to merge them all into a single library, but the issue still requires a fix.

**Comment by jessesaga** [comment]
Hi @vikram-rajan , I can't replicate this locally. What version of Mirth are you using?

**Comment by vikram-rajan** [comment]
Hi @jessesaga, I am on 3.9.1

Follow the below steps to replicate:

1. Add a dummy channel
2. Create multiple libraries and add some code templates from the Mirth GUI
3. Do a mirthsync pull
4. Delete of the code templates libraries from Mirth GUI - deploy all changes
5. Do a mirthsync push (using the code pulled from step 2)

**Comment by jessesaga** [comment]
Are you using mirthsync-2.0.7?

I can't replicate the error using these directions with mirth 3.9.0. I'll try against 3.9.1 soon..

**Comment by vikram-rajan** [comment]
yeah, I am using 2.0.7..
